### ISSUE TITLE
sp500_data.csv.gz  & kc_tax.csv.gz

### ISSUE THREAD

**Issue by mg-nyc** [gedeck/practical-statistics-for-data-scientists#11]
HI Peter 
i am new to this platform,python and your book. I was able to download all the data file to follow along except the two zip file above they an error 79- Inappropriate file type or format. I am on MAC (catalina) 10.15.6

please upload a better copy.
Thanks
![Screen Shot 2020-09-10 at 5 30 59 PM](https://user-images.githubusercontent.com/71097570/92810424-88d6be80-f38b-11ea-8586-6525b0e4bc81.png)

**Comment by gedeck** [comment]
The files are not zip files; they are gzipped files (GNU-zip). `gzip` (compress) and `gunzip` (uncompress) are available on Mac. I just downloaded the two files and checked if I can uncompress them using e.g. 
```
gunzip sp500_data.csv.gz
```
and it works without a problem. It seems that `Archive Utility` isn't handling this file correctly. 

When you look at the notebooks and the code, you will see that the files are read in the compressed form, e.g.
```
R: 
sp500_px <- read.csv(file.path(PSDS_PATH, 'data', 'sp500_data.csv.gz'), row.names=1)

Python:
SP500_DATA_CSV = DATA / 'sp500_data.csv.gz'
sp500_px = pd.read_csv(SP500_DATA_CSV, index_col=0)
```
so there is no need to uncompress them.

**Comment by mg-nyc** [comment]
do not see where to download it from. this must be the most undownloadable s/w . the site links are not clear enogh to follow along.    https://www.gzip.org/.

**Comment by mg-nyc** [comment]
never mind... was able to run in on terminal without having to download gunzip. Thanks
