### ISSUE TITLE
Data Issue: house_sales.csv

### ISSUE THREAD

**Issue by deulkkae** [gedeck/practical-statistics-for-data-scientists#14]
On 29 July 2020, [two data were added in house_sales.csv by gedeck](https://github.com/gedeck/practical-statistics-for-data-scientists/commit/49d6e318a1c0db4d3080ad47304d6d1cf21935d8). Those data's zip codes are 9800 and 89118. Because of them, many of the execution result of the codes in book, especially in Chapter 4, are not mached with Github code's. 9800 and 89118 are not even the zip codes of King County. They were not in the original data, printed book and in Learning O'Reiily contents. Are they really needed?

**Comment by gedeck** [comment]
Thanks for pointing it out. I remember that I removed these two data points as they were clearly incorrect and I must have reintroduced them by accident. I removed them now.

**Comment by deulkkae** [comment]
Thanks a lot!
