### ISSUE TITLE
Incorrect variable reference Chi2 (Chapter 3 page 127)

### ISSUE THREAD

**Issue by jcclark141152** [gedeck/practical-statistics-for-data-scientists#20]
The following code makes a variable call to the chi2 value calculated using the permutation test (chi2observed), vice the chi2 value computed using the scipy stats module (chisq).

chisq, pvalue, df, expected = stats.chi2_contingency(clicks)
print(f'Observed chi2: {chi2observed:.4f}')
print(f'p-value: {pvalue:.4f}')

I believe the first print line should be:
print(f'Observed chi2: {chisq:.4f}') since the purpose is to demonstrate using the chi2 module for statistical tests rather than the previous sections permutation test.

Thanks!

**Comment by gedeck** [comment]
Thank you for pointing this out. I'll correct the code and the book text.
