### ISSUE TITLE
Ch. 2 -  R Code Data and Sampling Distributions Lines 35, 36

### ISSUE THREAD

**Issue by dragula2022** [gedeck/practical-statistics-for-data-scientists#24]
I am getting an error with the three sampling examples in R version 4.1.0:
```
"Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'"
```

This error is also generated for the sample of 5 and sample of 20 starting on line 39 and 45.
I've fixed it by passing into the sample arguments loans_income$x, not just loans_income, based on the suggestion on this post: https://stackoverflow.com/questions/19648238/r-says-cannot-take-a-sample-larger-than-the-population-but-i-am-not-taking/19648272

I'm using R 4.1.0; but the arm64 version.

**Comment by gedeck** [comment]
I cannot reproduce the problem with R version 4.0.5. I have however an idea why you observe this problem. Here is the line that we use to get the `loans_income` data:
```
loans_income <- read.csv(file.path(PSDS_PATH, 'data', 'loans_income.csv'))[,1]
```
Note the extra slice operation `[,1]` that is applied to the result of `read.csv`. This converts the data frame to a vector in the same way your suggested modification `loans_income$x` does. 

It's easy to overlook the slice and it would be more obvious if we had used two lines for it in the code:
```
loans_income <- read.csv(file.path(PSDS_PATH, 'data', 'loans_income.csv'))
loans_income <- loans_income[, 1]   # convert data frame to vector
```
I'll make this modification.
