### ISSUE TITLE
Python code for Chapter 3 - Web Stickness - TypeError in the original code 

### ISSUE THREAD

**Issue by Slepetys** [gedeck/practical-statistics-for-data-scientists#36]
There is a TypeError running the Chapter 3 Web Stickness notebook:

The line:
`print(np.mean(perm_diffs > mean_b - mean_a))`

results in the following TypeError: _'>' not supported between instances of 'list' and 'float'_

which can be fixed using a mapObj such as:

```
mapObj = map(lambda _: _>(mean_b-mean_a), perm_diffs)
print (f'{sum(mapObj)*100/len(perm_diffs):4.2f}%')
```

**Comment by gedeck** [comment]
I cannot reproduce this issue with the latest versions of all modules. The difference to your code is that `mean_a` and `mean_b` are of type `numpy.float64` when I run the notebook. Your error message indicates that it is `float` in your case. There must be a difference in the Python environment. 

The same issue was reported a while ago #23 and #26, however we were not able to track it down to a specific version. The second report was using the M1 processor on a Mac. It could be that this causes the issue. Can you confirm what OS/hardware/Python versions you use?

In any case, I'm going to change the code as it seems to happen more often. I think your suggested code is too hard to read for new Python users. I will therefore use the following:
```
print(np.mean(np.array(perm_diffs) > mean_b - mean_a))
```
Can you confirm that it works for you?

**Comment by Slepetys** [comment]
Yes, it worked!

I am using an Intel i7 version 10 processor running Python 3.8.5 under Windows 10.

**Comment by gedeck** [comment]
So it's not the hardware. Can you run this command so that we can compare the package versions:
```
pip list --format=freeze 
```
Here is what I have currently installed using Python 3.10.4 
```
cycler==0.11.0
dmba==0.1.0
fonttools==4.33.2
future==0.18.2
imbalanced-learn==0.9.0
imblearn==0.0
joblib==1.1.0
kiwisolver==1.4.2
matplotlib==3.5.1
numpy==1.22.3
packaging==21.3
pandas==1.4.2
patsy==0.5.2
Pillow==9.1.0
pip==22.0.4
prince==0.7.1
progressbar2==4.0.0
pydotplus==2.0.2
pygam==0.8.0
pyparsing==3.0.8
python-dateutil==2.8.2
python-utils==3.1.0
pytz==2022.1
scikit-learn==1.0.2
scipy==1.8.0
seaborn==0.11.2
setuptools==58.1.0
six==1.16.0
statsmodels==0.13.2
threadpoolctl==3.1.0
wheel==0.37.1
wquantiles==0.6
xgboost==1.6.0
```

**Comment by Slepetys** [comment]
aiohttp==3.8.1
aiohttp-cors==0.7.0
aioredis==1.3.1
aiosignal==1.2.0
airbnb==2.3.2
alabaster==0.7.12
anaconda-client==1.9.0
anaconda-navigator==2.1.2
anaconda-project==0.10.2
ansicon==1.89.0
anyio==3.5.0
appdirs==1.4.4
argh==0.26.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==0.13.1
asn1crypto==1.4.0
astroid==2.6.6
astropy==5.0
async-generator==1.10
async-timeout==4.0.2
atomicwrites==1.4.0
attrs==21.4.0
autopep8==1.6.0
Babel==2.9.1
backcall==0.2.0
backports.functools-lru-cache==1.6.4
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.2.0
beautifulsoup4==4.10.0
binaryornot==0.4.4
bitarray==2.3.5
bkcharts==0.2
black==19.10b0
bleach==4.1.0
blessed==1.19.1
bokeh==2.4.2
boto==2.49.0
boto3==1.20.46
botocore==1.23.46
Bottleneck==1.3.2
brotlipy==0.7.0
browsercookie==0.7.7
bs4==0.0.1
cachetools==5.0.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.11
CityTime==1.0.0
click==8.0.4
cloudpickle==2.0.0
clyent==1.2.2
colorama==0.4.4
colorful==0.5.4
comtypes==1.1.10
conda==4.11.0
conda-build==3.20.5
conda-content-trust==0+unknown
conda-pack==0.6.0
conda-package-handling==1.7.3
conda-repo-cli==1.0.4
conda-token==0.3.0
conda-verify==3.4.2
contextlib2==0.6.0.post1
cookiecutter==1.7.2
crypto==1.4.1
cryptography==3.4.8
cssselect==1.1.0
cycler==0.11.0
Cython==0.29.25
cytoolz==0.11.0
daal4py==2021.5.0
dask==2021.10.0
DBnomics==1.2.2
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
diff-match-patch==20200713
distributed==2021.10.0
docutils==0.17.1
entrypoints==0.3
et-xmlfile==1.1.0
fake-useragent==0.1.11
fastcache==1.1.0
feedparser==6.0.8
filelock==3.4.2
flake8==3.9.2
Flask==1.1.2
fonttools==4.25.0
frozenlist==1.3.0
fsspec==2022.1.0
future==0.18.2
gevent==21.8.0
glob2==0.7
google-api-core==2.4.0
google-auth==2.5.0
googleapis-common-protos==1.54.0
gpustat==1.0.0b1
greenlet==1.1.1
grequests==0.6.0
grpcio==1.43.0
h5py==2.10.0
HeapDict==1.0.1
hiredis==2.0.0
html2text==2020.1.16
html5lib==1.1
idna==3.3
imagecodecs==2021.8.26
imageio==2.9.0
imagesize==1.3.0
importlib-metadata==4.8.2
inflection==0.5.1
iniconfig==1.1.1
intervaltree==3.1.0
ipykernel==6.4.1
ipython==7.31.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
isodate==0.6.0
isort==5.9.3
itsdangerous==2.0.1
jdcal==1.4.1
jedi==0.18.1
Jinja2==2.11.3
jinja2-time==0.2.0
jinxed==1.1.0
jmespath==0.10.0
joblib==1.1.0
json5==0.9.6
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.9.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server==1.13.5
jupyterlab==3.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==2.10.3
jupyterlab-widgets==1.0.0
keyring==23.4.0
kiwisolver==1.3.2
lazy-object-proxy==1.6.0
libarchive-c==2.9
llvmlite==0.37.0
locket==0.2.1
lxml==4.8.0
lz4==3.1.3
MarkupSafe==1.1.1
matplotlib==3.5.1
matplotlib-inline==0.1.2
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.3.1
mkl-random==1.2.2
mkl-service==2.4.0
mock==4.0.3
modin==0.13.0
modin-spreadsheet==0.1.2
more-itertools==8.12.0
mpmath==1.2.1
msgpack==1.0.2
multidict==6.0.2
multipledispatch==0.6.0
multitasking==0.0.9
munkres==1.1.4
mypy-extensions==0.4.3
Naked==0.1.31
navigator-updater==0.2.1
nbclassic==0.3.5
nbclient==0.5.11
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.6.3
nltk==3.7
nose==1.3.7
notebook==6.4.8
numba==0.54.1
numexpr==2.8.1
numpy==1.20.3
numpydoc==1.2
nvidia-ml-py3==7.352.0
olefile==0.46
opencensus==0.8.0
opencensus-context==0.1.2
OpenPermID==0.5
openpyxl==3.0.9
packaging==21.3
pandas==1.4.1
pandocfilters==1.5.0
paramiko==2.8.1
parse==1.19.0
parso==0.8.3
partd==1.2.0
path==16.2.0
pathlib2==2.3.6
pathspec==0.7.0
patsy==0.5.2
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
pip==21.2.2
pkginfo==1.8.2
pluggy==1.0.0
plumbum==1.7.2
ply==3.11
poyo==0.5.0
prometheus-client==0.13.1
prompt-toolkit==3.0.20
protobuf==3.19.4
psutil==5.8.0
ptyprocess==0.7.0
py==1.11.0
py-spy==0.3.11
pyarrow==6.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.7.0
pycosat==0.6.3
pycparser==2.21
pycryptodome==3.10.1
pycurl==7.44.1
pydocstyle==6.1.1
pyee==8.2.2
pyerfa==2.0.0
pyfiglet==0.8.post1
pyflakes==2.3.1
Pygments==2.11.2
PyJWT==2.1.0
pylint==2.9.6
pyls-spyder==0.4.0
PyNaCl==1.4.0
pyodbc==4.0.0-unsupported
pyOpenSSL==21.0.0
pyparsing==3.0.4
pypiwin32==223
pyppeteer==0.2.6
pyquery==1.4.3
pyreadline==2.1
pyrsistent==0.18.0
PySocks==1.7.1
pytest==6.2.5
python-dateutil==2.8.2
python-lsp-black==1.0.0
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.2.4
python-slugify==5.0.2
pytube==11.0.2
pytube3==9.6.4
pytz==2021.3
PyWavelets==1.1.1
pywin32==302
pywin32-ctypes==0.2.0
pywinpty==2.0.2
PyYAML==6.0
pyzmq==22.3.0
QDarkStyle==3.0.2Note: you may need to restart the kernel to use
updated packages.

qstylizer==0.1.10
QtAwesome==1.0.3
qtconsole==5.2.2
QtPy==1.11.2
ray==1.9.2
rdflib==6.0.0
redis==4.1.2
regex==2021.8.3
requests==2.27.1
requests-html==0.10.0
rope==0.22.0
rpyc==4.1.5
rsa==4.8
Rtree==0.9.7
ruamel-yaml-conda==0.15.100
s3transfer==0.5.0
scikit-image==0.18.3
scikit-learn==1.0.2
scikit-learn-intelex==2021.20220215.153006
scipy==1.7.3
seaborn==0.11.2
selenium==3.141.0
Send2Trash==1.8.0
setuptools==58.0.4
sgmllib3k==1.0.0
shellescape==3.8.1
simplegeneric==0.8.1
singledispatch==3.7.0
sip==4.19.13
six==1.16.0
smart-open==5.2.1
sniffio==1.2.0
snowballstemmer==2.2.0
sortedcollections==2.1.0
sortedcontainers==2.4.0
soupsieve==2.3.1
Sphinx==4.4.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib-websupport==1.2.4
spyder==5.1.5
spyder-kernels==2.1.3
SQLAlchemy==1.4.27
statsmodels==0.12.2
sympy==1.9
tables==3.6.1
tabulate==0.8.9
TBB==0.2
tblib==1.7.0
terminado==0.13.1
testpath==0.5.0
text-unidecode==1.3
textdistance==4.2.1
threadpoolctl==2.2.0
three-merge==0.1.1
tifffile==2021.7.2
tinycss==0.4
toml==0.10.2
toolz==0.11.2
tornado==6.1
tqdm==4.62.3
traitlets==5.1.1
typed-ast==1.4.3
typing-extensions==3.10.0.2
ujson==4.0.2
unicodecsv==0.14.1
Unidecode==1.2.0
urllib3==1.26.8
w3lib==1.22.0
watchdog==2.1.6
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.58.0
websockets==9.1
Werkzeug==2.0.3
wget==3.2
wheel==0.37.1
whichcraft==0.6.1
widgetsnbextension==3.5.2
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wquantiles==0.6
wrapt==1.12.1
xlrd==2.0.1
XlsxWriter==3.0.2
xlwings==0.24.9
xlwt==1.3.0
yahoo-fin==0.8.9.1
yapf==0.31.0
yarl==1.7.2
yfinance==0.1.70
youtube-dl==2021.6.6
zict==2.0.0
zipp==3.7.0
zope.event==4.5.0
zope.interface==5.4.0

Roberto Slepetys
+49 1511 502.1927 (whatsapp)

**Comment by gedeck** [comment]
I tried an environment using Python 3.8.5 with the same versions you used:
```
numpy==1.20.3
pandas==1.4.1
scipy==1.7.3
```
but see no problem with it. 

I'll make the change to ensure that the code works for you.
