### ISSUE TITLE
Different histogram under the same number of bins

### ISSUE THREAD

**Issue by hchen98** [gedeck/practical-statistics-for-data-scientists#38]
In chapter 1, the section where we talk about "Frequency Tables and Histograms", I tried to replicate the code of the histogram with a different Python package `lets-plot`, which should be similar hist() plot in r. However, the y-axis (the frequency) is different than what the R and Python generated under the same number of bins.

The histogram generated from the textbook code:
![image](https://user-images.githubusercontent.com/12217705/182687630-351c69c4-4a8d-4e44-8007-dc7b29f3ec92.png)

Code:
```
ax = (state['Population'] / 1_000_000).plot.hist(bins=10)  
ax.set_xlabel('Population (millions)')
```

The histogram generated by `lets-plot` (aka ggplot in Python):
![image](https://user-images.githubusercontent.com/12217705/182687816-11ddf598-7cef-41bd-a53f-6342c38d4867.png)

Code:

```
temp_df = pd.DataFrame(state['Population'] / 1_000_000)  
ggplot(temp_df, aes(x="Population")) + geom_histogram(bins=10)
```

**Comment by gedeck** [comment]
The shape of a histograms depends on how the bins are defined. You can see in the `lets-plot` graph that the left bin starts at around -2.5 and the right bin ends at about 40. For the pandas plot, the bins range from 0 to about 38. While it hardly changes the overall shape, the distribution of cases into the first two bins changes with the observed reversal in the column heights. 

If I compare the two graphs, I would say that the bins that `lets-plot` chooses are not appropriate for the data set. If you look at the `lets-plot` graph, the left most bin from -2.5 to 2.5, the population count is however only a positive number, so half of the bin range is not representing data. 

The documentation for `geom_histogram` (https://lets-plot.org/pages/api/lets_plot.geom_histogram.html) shows that there are keyword arguments that allow to control the positioning of the bins. Try using for example `boundary=0` and see how that changes the overall shape. 

If the datasets aren't too large, I like to use density plots. They often give a more informative picture of distributions.

Examples: 
- https://chartio.com/learn/charts/histogram-complete-guide/#choose-interpretable-bin-boundaries

**Comment by hchen98** [comment]
Hi @gedeck, thanks for replying to the issue so quickly. Oh dear, how careless I am to miss that detail :(  . I will close this issue since it's just my code error.
