### ISSUE TITLE
Possible Considerations on moving R into conda environment for consistency

### ISSUE THREAD

**Issue by gregorywaynepower** [gedeck/practical-statistics-for-data-scientists#40]
Due to conda being able to handle the R dependencies as well, I'd recommend adding the following to the existing environment file:

r-vioplot
r-corrplot
r-gmodels
r-matrixstats
r-lmperm
r-pwr
r-fnn
r-klar
r-dmwr
r-xgboost
r-ellipse
r-mclust
r-ca

Optional: add rstudio-desktop version that is more supported
conda install -c conda-forge rstudio-desktop compared to the rstudio-desktop version that is part of the default.

[Here's the link to the conda-forge version of rstudio-desktop.](https://anaconda.org/conda-forge/rstudio-desktop)

**Comment by gedeck** [comment]
Do you want to make a PR for this? I'm happy to add this.

**Comment by gregorywaynepower** [comment]
You got it! I have updated the README.md with new install instructions to reflect those changes as well. I also removed the call to install python from the `conda create` command since it's listed as a dependency in the environment.yml file to reduce redundancy.

**Comment by gedeck** [comment]
Thank you for your contribution!
