### ISSUE TITLE
Add R build to CI

### ISSUE THREAD

**Issue by gedeck** [gedeck/practical-statistics-for-data-scientists#48]
At a minimum make sure that the R code executes without a problem.

Example github action to run R
https://blog--simonpcouch.netlify.app/blog/r-github-actions-commit/

**Comment by gregorywaynepower** [comment]
Does GitHub support testing building through conda? If so, I could provide the requirements from Windows and Linux machines. I unfortunately don't have the ability to test requirements on MacOS though.

**Comment by gedeck** [comment]
That is a great link. I started a PR with a github action workflow for it #49. It builds a conda installation and then tries to load the data in `environment.yml`. It fails because it cannot handle the channel settings.

https://github.com/gedeck/practical-statistics-for-data-scientists/actions/runs/4147147029/jobs/7173670410
```
CondaValueError: could not parse '- conda-forge' in: environment.yml
```

I don't know how to handle this. If you have an idea what to do, please contribute to the PR
