### ISSUE TITLE
Resampling in chi square test

### ISSUE THREAD

**Issue by ribaptista** [gedeck/practical-statistics-for-data-scientists#51]
In this function:

https://github.com/gedeck/practical-statistics-for-data-scientists/blob/master/python/notebooks/Chapter%203%20-%20Statistical%20Experiments%20and%20Significance%20Testing.ipynb?short_path=69496c2#L873

```
def perm_fun(box):
    sample_clicks = [sum(random.sample(box, 1000)),
                     sum(random.sample(box, 1000)),
                     sum(random.sample(box, 1000))]
```

Shouldn't it be 
```
def perm_fun(box):
    random.shuffle(box)
    sample_clicks = [sum(box[0:1000]),
                     sum(box[1000:2000]),
                     sum(box[2000:3000])]
```

to ensure the total count of clicks is always 34?

**Comment by gedeck** [comment]
Hello, you are right. The Python code does not reflect the algorithm which describes a permutation test (resample without replacement). However, the with replacement approach could be used too. 

I'm going to add both versions to the notebook and adjust the version in the book to your method.
