### ISSUE TITLE
Figure 7.1 (Python) - Broken

### ISSUE THREAD

**Issue by willrod369** [gedeck/practical-statistics-for-data-scientists#55]
Using given code creates an error (1). 

Per Prince CA [documentation](https://maxhalford.github.io/prince/ca/), I was able to get it working (2).  

Python version: 3.11.4 (Using Jupyter Notebook)

------------------------------

**(1) Orignal Python Code & Error:**
  `housetasks = pd.read_csv(HOUSE_TASKS_CSV, index_col=0)
  
  ca = prince.CA(n_components=2)
  ca = ca.fit(housetasks)
  
  ca.plot_coordinates(housetasks, figsize=(6, 6))
  plt.tight_layout()
  plt.show()`

ERROR: AttributeError: 'CA' object has no attribute 'plot_coordinates'

**(2) Updated Python Code:** 
  `import pandas as pd
  import prince
  import altair as alt
  
  #Load the data
  housetasks = pd.read_csv(HOUSE_TASKS_CSV, index_col=0)
  
  #Create the model
  ca = prince.CA(n_components=2)
  
  #Fit the model
  ca = ca.fit(housetasks)
  
  #Extract the column coordinate dataframe, and change the column names
  cc = ca.column_coordinates(housetasks).reset_index()
  cc.columns = ['name', 'x', 'y']
  
  #Extract the row coordinates dataframe, and change the column names
  rc = ca.row_coordinates(housetasks).reset_index()
  rc.columns = ['name', 'x', 'y']
  
  #Combine the dataframes
  crc_df = pd.concat([cc, rc], ignore_index=True)
  
  #Plot and annotate
  points = ca.plot(housetasks, x_component=0, y_component=1)
  
  annot = alt.Chart(crc_df).mark_text(
      align='left',
      baseline='middle',
      fontSize = 10,
      dx = 7
  ).encode(
      x='x',
      y='y',
      text='name'
  )
  
  points + annot`

**Comment by gregorywaynepower** [comment]
@willrod369 Thanks for the feedback, they may have deprecated that parameter since that code what written. I can't speak for @gedeck but you're more thank welcome to make a pull request?

**Comment by gedeck** [comment]
The code was already adjusted two months ago:
```
from adjustText import adjust_text

housetasks = pd.read_csv(HOUSE_TASKS_CSV, index_col=0)

ca = prince.CA(n_components=2)
ca = ca.fit(housetasks)

ax = ca.row_coordinates(housetasks).plot.scatter(x=0, y=1, figsize=(6,6))
ca.column_coordinates(housetasks).plot.scatter(x=0, y=1, ax=ax, c='C1')
texts = []
for idx, row in ca.row_coordinates(housetasks).iterrows():
    texts.append(plt.text(row[0], row[1], idx))
for idx, row in ca.column_coordinates(housetasks).iterrows():
    texts.append(plt.text(row[0], row[1], idx, color='C1'))
adjust_text(texts, only_move={'points':'y', 'texts':'y'}) 
plt.tight_layout()
plt.show()
```

**Comment by willrod369** [comment]
Makes sense. I downloaded the repo 4/19. 

Thanks!
