### ISSUE TITLE
Anaconda - ResolvePackageNotFound

### ISSUE THREAD

**Issue by kotturi-mahipal** [gedeck/practical-statistics-for-data-scientists#56]
I was trying to clone the repo and run the Python files. While updating the _environment.yml_ file after creating the **_sfds_**, I got this below shown error.
![Screenshot from 2023-06-29 16-58-41](https://github.com/gedeck/practical-statistics-for-data-scientists/assets/109608873/e46b7b86-2742-489c-be8e-ac08ffd782ec)

**Comment by gregorywaynepower** [comment]
Hey @kotturi-mahipal were you able to install dmba, pygram r-vioplot, wquantiles, and adjusttext manually after the update?

Also, what operating system are you on?

**Comment by fx-biocoder** [comment]
Hey, I've had the same issue. I've solved it using [conda-forge](https://conda-forge.org/). Just run these commands inside the environment:

```bash
$ conda config --add channels conda-forge
$ conda config --set channel_priority strict
$ conda install <package-name>
```

Hope this helps!
