### ISSUE TITLE
Graphs in Chapter 5 Classification are not displaying in the Jupyter Notebook

### ISSUE THREAD

**Issue by SSJUSA** [gedeck/practical-statistics-for-data-scientists#6]
Jupyter Notebook program of Chapter 5 Classification is giving following errors:

Matplotlib is currently using agg, which is a non-GUI backend, so can't show the figure.

Please fix these errors and update notebook's code files on this book's Github webpage.

Thanks and best regards,
SSJ

**Comment by gedeck** [comment]
The code was missing the line:
```
%matplotlib inline
```
It got stripped in the process that is used to create the notebook.

**Comment by gedeck** [comment]
Please try with the new version of the notebook

**Comment by SSJUSA** [comment]
Thank you.
That worked

**Comment by gedeck** [comment]
Excellent. I close the issue
