### ISSUE TITLE
Chapter 7 Unsupervised Learning  Cell #18 Dendrogram is giving error

### ISSUE THREAD

**Issue by SSJUSA** [gedeck/practical-statistics-for-data-scientists#8]
Chapter 7 Unsupervised Learning 
Cell #18 Dendrogram is giving following error:

Please fix the error and upload corrected code to Github web page.
Thanks

ValueError                                Traceback (most recent call last)
<ipython-input-18-55ef65bee9a5> in <module>
      1 fig, ax = plt.subplots(figsize=(5, 5))
      2 
----> 3 dendrogram(Z, labels=df.index, color_threshold=0)
      4 plt.xticks(rotation=90)
      5 ax.set_ylabel('distance')

C:\ProgramData\Anaconda3\lib\site-packages\scipy\cluster\hierarchy.py in dendrogram(Z, p, truncate_mode, color_threshold, get_leaves, orientation, labels, count_sort, distance_sort, show_leaf_counts, no_plot, no_labels, leaf_font_size, leaf_rotation, leaf_label_func, show_contracted, link_color_func, ax, above_threshold_color)
   3275                          "'bottom', or 'right'")
   3276 
-> 3277     if labels and Z.shape[0] + 1 != len(labels):
   3278         raise ValueError("Dimensions of Z and labels must be consistent.")
   3279 

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in __nonzero__(self)
   2148     def __nonzero__(self):
   2149         raise ValueError(
-> 2150             f"The truth value of a {type(self).__name__} is ambiguous. "
   2151             "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
   2152         )

ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by gedeck** [comment]
As you can see in the [rendering of the notebook](https://github.com/gedeck/practical-statistics-for-data-scientists/blob/master/python/notebooks/Chapter%207%20-%20Unsupervised%20Learning.ipynb), the code works without an error on my setup. I've just rebuilt the network with a fresh environment, but never had a problem with previous packages. 

Can you first test if the notebook builds without an error when you restart the Kernel and run all? 
If that still leads to a failure, can you send me the output of `conda list` so that I can see the versions you were using.

**Comment by SSJUSA** [comment]
Thank you for your email.

I am running this notebook on a Windows 10 laptop with NVIDIA GPU processor.

Below is the conda list from my laptop computer.

Thanks,



Microsoft Windows [Version 10.0.18363.959]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>conda list
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
altair                    4.1.0                    pypi_0    pypi
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.12                   py37_0
appdirs                   1.4.4                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     19.3.0                     py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
beautifulsoup4            4.9.1                    py37_0
black                     19.10b0                  pypi_0    pypi
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
brotlipy                  0.7.0           py37he774522_1000
bzip2                     1.0.8                he774522_0
ca-certificates           2020.6.24                     0
cachetools                4.1.1                    pypi_0    pypi
catalogue                 1.0.0                    py37_1
certifi                   2020.6.20                py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.3                      py_0
colour                    0.1.5                    pypi_0    pypi
conda                     4.8.3                    py37_0
conda-build               3.18.11                  py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.6.1            py37h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
cryptography              2.9.2            py37h7a1dbc1_0
cycler                    0.10.0                   py37_0
cymem                     2.0.3            py37ha925a31_0
cython-blis               0.4.1            py37he774522_1
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
dill                      0.3.2                    pypi_0    pypi
dmba                      0.0.12                   pypi_0    pypi
en-core-web-lg            2.3.1                    pypi_0    pypi
en-core-web-sm            2.3.1                    pypi_0    pypi
entrypoints               0.3                      py37_0
filelock                  3.0.12                     py_0
freetype                  2.10.2               hd328e21_0
future                    0.18.2                   py37_1
geojson                   2.5.0                    pypi_0    pypi
glob2                     0.7                        py_0
google-auth               1.19.2                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
graphviz                  2.38                 hfd603c8_2
great-expectations        0.11.8                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imbalanced-learn          0.7.0                    pypi_0    pypi
imblearn                  0.0                      pypi_0    pypi
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intel-openmp              2020.1                      216
ipykernel                 5.3.0            py37h5ca1d4c_0
ipython                   7.16.1           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
jedi                      0.17.1                   py37_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.0.2                    py37_0
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
kiwisolver                1.2.0            py37h74a9793_0
libarchive                3.4.2                h5e25573_0
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.1.0                h56a325e_1
libxml2                   2.9.10               h464c3ec_1
lime                      0.2.0.1                  pypi_0    pypi
lz4-c                     1.9.2                h62dcd97_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_1
marshmallow               3.7.1                    pypi_0    pypi
matplotlib                3.3.0                    pypi_0    pypi
matplotlib-base           3.2.2            py37h64f37c6_0
menuinst                  1.4.16           py37he774522_1
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
mlxtend                   0.17.2                   pypi_0    pypi
mpld3                     0.5.1                    pypi_0    pypi
msys2-conda-epoch         20160418                      1
murmurhash                1.0.2            py37h33f27b4_0
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
notebook                  6.0.3                    py37_0
numpy                     1.19.0                   pypi_0    pypi
numpy-base                1.18.5           py37hc3f5095_0
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0
openssl                   1.1.1g               he774522_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.4                       py_0
pandarallel               1.4.8                    pypi_0    pypi
pandas                    1.0.5            py37h47e9c7a_0
pandas-datareader         0.9.0                    pypi_0    pypi
pandoc                    2.10                          0
pandocfilters             1.4.2                    py37_1
parso                     0.7.0                      py_0
pathspec                  0.8.0                    pypi_0    pypi
patsy                     0.5.1                    py37_0
pickleshare               0.7.5                 py37_1001
pillow                    7.2.0            py37hcc1f983_0
pip                       20.1.1                   py37_1
pixiedust                 1.1.18                   pypi_0    pypi
pkginfo                   1.5.0.1                  py37_0
plac                      0.9.6                    py37_1
powershell_shortcut       0.0.1                         3
preshed                   3.0.2            py37h33f27b4_1
prince                    0.7.0                    pypi_0    pypi
progressbar2              3.51.4                   pypi_0    pypi
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
psutil                    5.7.0            py37he774522_0
py-lief                   0.10.1           py37ha925a31_0
pyarrow                   1.0.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycosat                   0.6.3            py37he774522_0
pycparser                 2.20                       py_2
pydotplus                 2.0.2                      py_3
pygam                     0.8.0                    pypi_0    pypi
pygments                  2.6.1                      py_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyphen                    0.9.5                    pypi_0    pypi
pyprind                   2.11.2                   pypi_0    pypi
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.16.0           py37he774522_0
pysocks                   1.7.1                    py37_1
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                      py_0
python-graphviz           0.14.1                   pypi_0    pypi
python-libarchive-c       2.9                        py_0
python-utils              2.4.0                    pypi_0    pypi
pytz                      2020.1                     py_0
pywin32                   227              py37he774522_1
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.1           py37ha925a31_1
qt                        5.9.7            vc14h73c81de_0
qtpy                      1.9.0                      py_0
requests                  2.23.0                   pypi_0    pypi
requests-cache            0.5.2                    pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
ruamel-yaml               0.16.10                  pypi_0    pypi
ruamel-yaml-clib          0.2.0                    pypi_0    pypi
ruamel_yaml               0.15.87          py37he774522_1
scikit-learn              0.23.1           py37h25d0782_0
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py37_0
setuptools                49.2.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
soupsieve                 2.0.1                      py_0
spacy                     2.3.1            py37h74a9793_0
sqlite                    3.32.3               h2a8f88b_0
srsly                     1.0.2            py37ha925a31_0
statsmodels               0.11.1           py37he774522_0
swifter                   0.305                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow-gpu            2.2.0                    pypi_0    pypi
tensorflow-gpu-estimator  2.2.0                    pypi_0    pypi
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
thinc                     7.4.1            py37h74a9793_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               he774522_0
toml                      0.10.1                   pypi_0    pypi
tornado                   6.0.4            py37he774522_1
tqdm                      4.47.0                     py_0
traitlets                 4.3.3                    py37_0
typed-ast                 1.4.1                    pypi_0    pypi
tzlocal                   2.1                      pypi_0    pypi
umap-learn                0.4.6                    pypi_0    pypi
urllib3                   1.25.9                     py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wasabi                    0.6.0                      py_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wquantiles                0.5                      pypi_0    pypi
xgboost                   1.1.1                    pypi_0    pypi
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zeromq                    4.3.2                ha925a31_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                ha9fde0e_0

C:\WINDOWS\system32>

**Comment by gedeck** [comment]
I rerun chapter 7 with a fresh install using Python 3.7 and still cannot reproduce your problem. The version numbers of the various packages mostly identical and only few differ by one in the minor version numbers. As I haven't changed this code for a long time, I doubt that it would be an odd combination of these. 

Do you see the problem after restarting the kernel and rerunning all code?

![image](https://user-images.githubusercontent.com/8720575/89126377-3c0de700-d4b3-11ea-980e-aa35b253b789.png)

According to the traceback you pasted, the failing test points to an inconsistency between the linkage results `Z` and the length of `df.index` (variable label). Here are the sizes of the two:

![image](https://user-images.githubusercontent.com/8720575/89126517-19c89900-d4b4-11ea-8706-fe68fdf6d75b.png)

As you can see, the condition `if labels and Z.shape[0] + 1 != len(labels):` is not `True` in this case. `Z.shape[0]` is 17 and `len(labels)` is 18, one more which is the requirement for the `dendrogram` method. What are these values in your case? What is `df.index`? It should be identical to `syms1` in the box before.

**Comment by SSJUSA** [comment]
Thank you for your email.
Restarting the Kernel and rerunning all code did not solve the problem.

I have searched Google and found the following link:

https://github.com/dask/fastparquet/issues/172

This link says the following:

the df.columns is actually an index. what does work is
df.columns.values.tolist()

So I have replaced Cell #18 code line with the following and it displayed
the Dendrogram:

dendrogram(Z, labels=df.index.values.tolist(), color_threshold=0)

Please use this code line on your computer and see if it works on your
computer?

Again, thank you for communicating with me.

Best regards,
SSJ

**Comment by SSJUSA** [comment]
I also have following #s and I got the error

(17, 4)
18
(18, 1131)


Following code line fixed the error:

dendrogram(Z, labels=df.index.values.tolist(), color_threshold=0)


https://github.com/dask/fastparquet/issues/172

**Comment by gedeck** [comment]
I'm really puzzled by this. These are the first lines in dendrogram.
```
    Z = np.asarray(Z, order='c')

    if orientation not in ["top", "left", "bottom", "right"]:
        raise ValueError("orientation must be one of 'top', 'left', "
                         "'bottom', or 'right'")

    if labels is not None and Z.shape[0] + 1 != len(labels):
        raise ValueError("Dimensions of Z and labels must be consistent.")
```
`Z` is already a numpy array, so I don't expect any change here. Could you print the following lines:
```
print(np.asarray(Z, order='c').shape)
print(labels is not None)
print(Z.shape[0] + 1, len(labels))
print(Z.shape[0] + 1 != len(labels))
print(labels is not None and Z.shape[0] + 1 != len(labels))
Zc = np.asarray(Z, order='c')
print(Zc.shape[0] + 1, len(labels))
print(Zc.shape[0] + 1 != len(labels))
print(labels is not None and Zc.shape[0] + 1 != len(labels))
```
and also these commands:
```
print(df.index)
print(df.index.values)
print(df.index.values.tolist())
print(len(df.index))
print(len(df.index.values))
print(len(df.index.values.tolist()))
```
I get the following: 
```
Index(['AAPL', 'AMZN', 'AXP', 'COP', 'COST', 'CSCO', 'CVX', 'GOOGL', 'HD',
       'INTC', 'JPM', 'MSFT', 'SLB', 'TGT', 'USB', 'WFC', 'WMT', 'XOM'],
      dtype='object')
['AAPL' 'AMZN' 'AXP' 'COP' 'COST' 'CSCO' 'CVX' 'GOOGL' 'HD' 'INTC' 'JPM'
 'MSFT' 'SLB' 'TGT' 'USB' 'WFC' 'WMT' 'XOM']
['AAPL', 'AMZN', 'AXP', 'COP', 'COST', 'CSCO', 'CVX', 'GOOGL', 'HD', 'INTC', 'JPM', 'MSFT', 'SLB', 'TGT', 'USB', 'WFC', 'WMT', 'XOM']
18
18
18
```

**Comment by SSJUSA** [comment]
Thank you for your email.

In addition to the prints you have asked for, I have added couple of more
prints to dendrogram function as given at the end of this email:

      print(labels)
      print((Z.shape[0] + 1) != len(labels))

I have attached two files to this email, html version of notebook and pdf
named (i.e. changed html extension to pdf extension to avoid filtering)

Cell #20 and Cell # 26 are similar except dendrogram function call
statements.

Cell #20 is successful and showing dendrogram figure:

dendrogram(Z, labels=df.index.values.tolist(), color_threshold=0)

(17, 4)
True
18 18
False
False
18 18
False
False
['AAPL', 'AMZN', 'AXP', 'COP', 'COST', 'CSCO', 'CVX', 'GOOGL', 'HD',
'INTC', 'JPM', 'MSFT', 'SLB', 'TGT', 'USB', 'WFC', 'WMT', 'XOM']
False

[image: image.png]

For the print(labels) statement above we are getting list whereas for below
statement it is giving index object output as shown below:

Cell #26 call statement is failing and giving different output for
print(labels)  statement:

dendrogram(Z, labels=df.index, color_threshold=0)

(17, 4)
True
18 18
False
False
18 18
False
False
Index(['AAPL', 'AMZN', 'AXP', 'COP', 'COST', 'CSCO', 'CVX', 'GOOGL', 'HD',
       'INTC', 'JPM', 'MSFT', 'SLB', 'TGT', 'USB', 'WFC', 'WMT', 'XOM'],
      dtype='object')
False


So I think, it is version of pandas that is different from your computer
and my laptop is causing this error?
my version of pandas is   1.0.5
What is your version?

Is Pandas version causing this error?

Thanks and best regards,
SSJ


    Z = np.asarray(Z, order='c')

    print(np.asarray(Z, order='c').shape)
    print(labels is not None)
    print(Z.shape[0] + 1, len(labels))
    print(Z.shape[0] + 1 != len(labels))
    print(labels is not None and Z.shape[0] + 1 != len(labels))
    Zc = np.asarray(Z, order='c')
    print(Zc.shape[0] + 1, len(labels))
    print(Zc.shape[0] + 1 != len(labels))
    print(labels is not None and Zc.shape[0] + 1 != len(labels))
    print(labels)
    print((Z.shape[0] + 1) != len(labels))

    if orientation not in ["top", "left", "bottom", "right"]:
        raise ValueError("orientation must be one of 'top', 'left', "
                         "'bottom', or 'right'")

    if (labels and ((Z.shape[0] + 1) != len(labels))):
        raise ValueError("Dimensions of Z and labels must be consistent.")

**Comment by gedeck** [comment]
The attached files were filtered out. Can you please use the website to share the files?

**Comment by gedeck** [comment]
My Pandas version is 1.1.0

**Comment by SSJUSA** [comment]
I do not know how to share files using website.

Can you tell me some steps on how to share please?

Thanks

**Comment by gedeck** [comment]
Got to the github site https://github.com/gedeck/practical-statistics-for-data-scientists/issues/8
and drop the file into the textbox

**Comment by SSJUSA** [comment]
[Ch07_Unsup_LRNG.zip](https://github.com/gedeck/practical-statistics-for-data-scientists/files/5031951/Ch07_Unsup_LRNG.zip)

**Comment by SSJUSA** [comment]
Yes, dropped zip file.
Please see if you can access and read it.

Thanks

**Comment by gedeck** [comment]
I was finally able to reproduce the issue with my installation. I think it was due to changes in pandas with respect to the data frame index. The following modification works:
```
fig, ax = plt.subplots(figsize=(5, 5))
dendrogram(Z, labels=list(df.index), color_threshold=0)
plt.xticks(rotation=90)
ax.set_ylabel('distance')
```
Note, the conversion of the index to a standard Python list.
